#pragma once

#define NAMESPACE_MUMBI_BEGIN	namespace mumbi {
#define NAMESPACE_MUMBI_END		}

#define NAMESPACE_NET_BEGIN		namespace net {
#define NAMESPACE_NET_END		}

#define NAMESPACE_MUMBI_NET_BEGIN	NAMESPACE_MUMBI_BEGIN	NAMESPACE_NET_BEGIN
#define NAMESPACE_MUMBI_NET_END		NAMESPACE_NET_END		NAMESPACE_MUMBI_END


